# Copyright 2010 - 2011, Qualcomm Innovation Center, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
# 

Import('env')

# Plugin library sources
srcs = env.Glob('*.cc')
if '' != env.subst('$GECKO_BASE'):
    env.MergeFlags(['-I. -Inpapi -I$GECKO_BASE/include'])
    srcs.append(env.Glob('npapi/*.cc'))
else:
    env.MergeFlags(['-I. -Icordova'])
    srcs.append(env.Glob('cordova/*.cc'))
    srcs.append(env.Glob('cordova/${OS_CONF}/*.cc'))
srcs.append(env.Glob('os/${OS_CONF}/*.cc'))

objs = env.SharedObject(srcs)
if env['OS_CONF'] == 'windows':
    objs.append(['os/${OS_CONF}/npalljoyn.def', env.RES('os/${OS_CONF}/npalljoyn.rc')])

# Plugin library
npalljoyn = env.SharedLibrary('npalljoyn', objs)
shlibs = ['npalljoyn']

Return(shlibs)
